/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.trackedout.client.apis

import java.io.IOException
import okhttp3.OkHttpClient
import okhttp3.HttpUrl

import org.trackedout.client.models.Claim
import org.trackedout.client.models.ClaimsGet200Response
import org.trackedout.client.models.Error

import com.squareup.moshi.Json

import org.trackedout.client.infrastructure.ApiClient
import org.trackedout.client.infrastructure.ApiResponse
import org.trackedout.client.infrastructure.ClientException
import org.trackedout.client.infrastructure.ClientError
import org.trackedout.client.infrastructure.ServerException
import org.trackedout.client.infrastructure.ServerError
import org.trackedout.client.infrastructure.MultiValueMap
import org.trackedout.client.infrastructure.PartConfig
import org.trackedout.client.infrastructure.RequestConfig
import org.trackedout.client.infrastructure.RequestMethod
import org.trackedout.client.infrastructure.ResponseType
import org.trackedout.client.infrastructure.Success
import org.trackedout.client.infrastructure.toMultiValue

class ClaimApi(basePath: kotlin.String = defaultBasePath, client: OkHttpClient = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "http://localhost:3000/v1")
        }
    }

    /**
     * Add a claim
     * Add a claim for a player
     * @param claim 
     * @return Claim
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun claimsAddClaimPost(claim: Claim) : Claim {
        val localVarResponse = claimsAddClaimPostWithHttpInfo(claim = claim)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as Claim
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Add a claim
     * Add a claim for a player
     * @param claim 
     * @return ApiResponse<Claim?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun claimsAddClaimPostWithHttpInfo(claim: Claim) : ApiResponse<Claim?> {
        val localVariableConfig = claimsAddClaimPostRequestConfig(claim = claim)

        return request<Claim, Claim>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation claimsAddClaimPost
     *
     * @param claim 
     * @return RequestConfig
     */
    fun claimsAddClaimPostRequestConfig(claim: Claim) : RequestConfig<Claim> {
        val localVariableBody = claim
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/claims/add-claim",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * Delete a claim
     * Remove a claim from a player&#39;s deck. If multiple copies of this claim exist, only one will be removed.
     * @param claim 
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun claimsDeleteClaimPost(claim: Claim) : Unit {
        val localVarResponse = claimsDeleteClaimPostWithHttpInfo(claim = claim)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Delete a claim
     * Remove a claim from a player&#39;s deck. If multiple copies of this claim exist, only one will be removed.
     * @param claim 
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun claimsDeleteClaimPostWithHttpInfo(claim: Claim) : ApiResponse<Unit?> {
        val localVariableConfig = claimsDeleteClaimPostRequestConfig(claim = claim)

        return request<Claim, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation claimsDeleteClaimPost
     *
     * @param claim 
     * @return RequestConfig
     */
    fun claimsDeleteClaimPostRequestConfig(claim: Claim) : RequestConfig<Claim> {
        val localVariableBody = claim
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/claims/delete-claim",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * Get all claims
     * Only admins can retrieve all claims.
     * @param player Player (optional)
     * @param state Claim state (optional)
     * @param type Claim type (optional)
     * @param claimant Claimant (optional)
     * @param sortBy sort by query in the form of field:desc/asc (ex. name:asc) (optional)
     * @param projectBy project by query in the form of field:hide/include (ex. name:hide) (optional)
     * @param limit Maximum number of claims (optional)
     * @param page Page number (optional, default to 1)
     * @return ClaimsGet200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun claimsGet(player: kotlin.String? = null, state: kotlin.String? = null, type: kotlin.String? = null, claimant: kotlin.String? = null, sortBy: kotlin.String? = null, projectBy: kotlin.String? = null, limit: kotlin.Int? = null, page: kotlin.Int? = 1) : ClaimsGet200Response {
        val localVarResponse = claimsGetWithHttpInfo(player = player, state = state, type = type, claimant = claimant, sortBy = sortBy, projectBy = projectBy, limit = limit, page = page)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ClaimsGet200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Get all claims
     * Only admins can retrieve all claims.
     * @param player Player (optional)
     * @param state Claim state (optional)
     * @param type Claim type (optional)
     * @param claimant Claimant (optional)
     * @param sortBy sort by query in the form of field:desc/asc (ex. name:asc) (optional)
     * @param projectBy project by query in the form of field:hide/include (ex. name:hide) (optional)
     * @param limit Maximum number of claims (optional)
     * @param page Page number (optional, default to 1)
     * @return ApiResponse<ClaimsGet200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun claimsGetWithHttpInfo(player: kotlin.String?, state: kotlin.String?, type: kotlin.String?, claimant: kotlin.String?, sortBy: kotlin.String?, projectBy: kotlin.String?, limit: kotlin.Int?, page: kotlin.Int?) : ApiResponse<ClaimsGet200Response?> {
        val localVariableConfig = claimsGetRequestConfig(player = player, state = state, type = type, claimant = claimant, sortBy = sortBy, projectBy = projectBy, limit = limit, page = page)

        return request<Unit, ClaimsGet200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation claimsGet
     *
     * @param player Player (optional)
     * @param state Claim state (optional)
     * @param type Claim type (optional)
     * @param claimant Claimant (optional)
     * @param sortBy sort by query in the form of field:desc/asc (ex. name:asc) (optional)
     * @param projectBy project by query in the form of field:hide/include (ex. name:hide) (optional)
     * @param limit Maximum number of claims (optional)
     * @param page Page number (optional, default to 1)
     * @return RequestConfig
     */
    fun claimsGetRequestConfig(player: kotlin.String?, state: kotlin.String?, type: kotlin.String?, claimant: kotlin.String?, sortBy: kotlin.String?, projectBy: kotlin.String?, limit: kotlin.Int?, page: kotlin.Int?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (player != null) {
                    put("player", listOf(player.toString()))
                }
                if (state != null) {
                    put("state", listOf(state.toString()))
                }
                if (type != null) {
                    put("type", listOf(type.toString()))
                }
                if (claimant != null) {
                    put("claimant", listOf(claimant.toString()))
                }
                if (sortBy != null) {
                    put("sortBy", listOf(sortBy.toString()))
                }
                if (projectBy != null) {
                    put("projectBy", listOf(projectBy.toString()))
                }
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
                if (page != null) {
                    put("page", listOf(page.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/claims",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * Edit a claim
     * Add a claim for a player
     * @param id Claim ID
     * @param claim 
     * @return Claim
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun claimsIdPatch(id: kotlin.String, claim: Claim) : Claim {
        val localVarResponse = claimsIdPatchWithHttpInfo(id = id, claim = claim)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as Claim
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Edit a claim
     * Add a claim for a player
     * @param id Claim ID
     * @param claim 
     * @return ApiResponse<Claim?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun claimsIdPatchWithHttpInfo(id: kotlin.String, claim: Claim) : ApiResponse<Claim?> {
        val localVariableConfig = claimsIdPatchRequestConfig(id = id, claim = claim)

        return request<Claim, Claim>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation claimsIdPatch
     *
     * @param id Claim ID
     * @param claim 
     * @return RequestConfig
     */
    fun claimsIdPatchRequestConfig(id: kotlin.String, claim: Claim) : RequestConfig<Claim> {
        val localVariableBody = claim
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PATCH,
            path = "/claims/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * Batch update or insert claims
     * Batch update or insert claims
     * @param claim 
     * @return ClaimsGet200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun claimsPost(claim: kotlin.collections.List<Claim>) : ClaimsGet200Response {
        val localVarResponse = claimsPostWithHttpInfo(claim = claim)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ClaimsGet200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Batch update or insert claims
     * Batch update or insert claims
     * @param claim 
     * @return ApiResponse<ClaimsGet200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun claimsPostWithHttpInfo(claim: kotlin.collections.List<Claim>) : ApiResponse<ClaimsGet200Response?> {
        val localVariableConfig = claimsPostRequestConfig(claim = claim)

        return request<kotlin.collections.List<Claim>, ClaimsGet200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation claimsPost
     *
     * @param claim 
     * @return RequestConfig
     */
    fun claimsPostRequestConfig(claim: kotlin.collections.List<Claim>) : RequestConfig<kotlin.collections.List<Claim>> {
        val localVariableBody = claim
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/claims",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
