/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.trackedout.client.models

import org.trackedout.client.models.Token

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param access 
 * @param refresh 
 */


data class AuthTokens (

    @Json(name = "access")
    val access: Token? = null,

    @Json(name = "refresh")
    val refresh: Token? = null

)

