/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.trackedout.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param name 
 * @param email must be unique
 * @param password At least one number and one letter
 */


data class EventsIdPatchRequest (

    @Json(name = "name")
    val name: kotlin.String? = null,

    /* must be unique */
    @Json(name = "email")
    val email: kotlin.String? = null,

    /* At least one number and one letter */
    @Json(name = "password")
    val password: kotlin.String? = null

)

