/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.trackedout.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param name 
 * @param player 
 * @param server 
 * @param deckType 
 * @param hiddenInDecks 
 */


data class Item (

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "player")
    val player: kotlin.String? = null,

    @Json(name = "server")
    val server: kotlin.String? = null,

    @Json(name = "deckType")
    val deckType: kotlin.String? = null,

    @Json(name = "hiddenInDecks")
    val hiddenInDecks: kotlin.collections.List<kotlin.String>? = null

)

