/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.trackedout.client.models

import org.trackedout.client.models.StatusSectionLinesInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param header 
 * @param lines 
 */


data class StatusSection (

    @Json(name = "header")
    val header: kotlin.String? = null,

    @Json(name = "lines")
    val lines: kotlin.collections.List<StatusSectionLinesInner>? = null

)

