/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.trackedout.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param type 
 * @param arguments 
 * @param targetPlayer 
 * @param server 
 * @param sourceIP 
 */


data class Task (

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "type")
    val type: kotlin.String? = null,

    @Json(name = "arguments")
    val arguments: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "targetPlayer")
    val targetPlayer: kotlin.String? = null,

    @Json(name = "server")
    val server: kotlin.String? = null,

    @Json(name = "sourceIP")
    val sourceIP: kotlin.String? = null

)

