/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.trackedout.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param token 
 * @param expires 
 */


data class Token (

    @Json(name = "token")
    val token: kotlin.String? = null,

    @Json(name = "expires")
    val expires: java.time.OffsetDateTime? = null

)

