/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.trackedout.client.models

import org.trackedout.client.models.AuthTokens
import org.trackedout.client.models.User

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param user 
 * @param tokens 
 */


data class UserWithTokens (

    @Json(name = "user")
    val user: User? = null,

    @Json(name = "tokens")
    val tokens: AuthTokens? = null

)

