# Name of the action
name: Automatic Release

# Event to run on
on:
  # Will run on every push in the "main" branch
  push:
    branches:
      - main

permissions:
  contents: write

# Jobs that will execute
jobs:
  release:
    name: Setup Environment, Build JAR and Release Project
    runs-on: ubuntu-latest
    steps:
      - name: Automatic Release
        uses: Fulminazzo/java-automatic-release@v1
        with:
          java-version: 17
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY_NAME: ${{ github.event.repository.name }}
          # Message specified in the commit
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
